/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as EfeitosRouteImport } from './routes/efeitos'
import { Route as CronologiaRouteImport } from './routes/cronologia'
import { Route as CalculadoraRouteImport } from './routes/calculadora'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicV1SimulateRouteImport } from './routes/api/public/v1/simulate'
import { Route as ApiPublicV1RecommendIntervalRouteImport } from './routes/api/public/v1/recommend-interval'
import { Route as ApiPublicV1MontecarloRouteImport } from './routes/api/public/v1/montecarlo'
import { Route as ApiPublicV1HealthRouteImport } from './routes/api/public/v1/health'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'

const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const EfeitosRoute = EfeitosRouteImport.update({
  id: '/efeitos',
  path: '/efeitos',
  getParentRoute: () => rootRouteImport,
} as any)
const CronologiaRoute = CronologiaRouteImport.update({
  id: '/cronologia',
  path: '/cronologia',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculadoraRoute = CalculadoraRouteImport.update({
  id: '/calculadora',
  path: '/calculadora',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1SimulateRoute = ApiPublicV1SimulateRouteImport.update({
  id: '/api/public/v1/simulate',
  path: '/api/public/v1/simulate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1RecommendIntervalRoute =
  ApiPublicV1RecommendIntervalRouteImport.update({
    id: '/api/public/v1/recommend-interval',
    path: '/api/public/v1/recommend-interval',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicV1MontecarloRoute = ApiPublicV1MontecarloRouteImport.update({
  id: '/api/public/v1/montecarlo',
  path: '/api/public/v1/montecarlo',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1HealthRoute = ApiPublicV1HealthRouteImport.update({
  id: '/api/public/v1/health',
  path: '/api/public/v1/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calculadora': typeof CalculadoraRoute
  '/cronologia': typeof CronologiaRoute
  '/efeitos': typeof EfeitosRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/v1/health': typeof ApiPublicV1HealthRoute
  '/api/public/v1/montecarlo': typeof ApiPublicV1MontecarloRoute
  '/api/public/v1/recommend-interval': typeof ApiPublicV1RecommendIntervalRoute
  '/api/public/v1/simulate': typeof ApiPublicV1SimulateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calculadora': typeof CalculadoraRoute
  '/cronologia': typeof CronologiaRoute
  '/efeitos': typeof EfeitosRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/v1/health': typeof ApiPublicV1HealthRoute
  '/api/public/v1/montecarlo': typeof ApiPublicV1MontecarloRoute
  '/api/public/v1/recommend-interval': typeof ApiPublicV1RecommendIntervalRoute
  '/api/public/v1/simulate': typeof ApiPublicV1SimulateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calculadora': typeof CalculadoraRoute
  '/cronologia': typeof CronologiaRoute
  '/efeitos': typeof EfeitosRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/v1/health': typeof ApiPublicV1HealthRoute
  '/api/public/v1/montecarlo': typeof ApiPublicV1MontecarloRoute
  '/api/public/v1/recommend-interval': typeof ApiPublicV1RecommendIntervalRoute
  '/api/public/v1/simulate': typeof ApiPublicV1SimulateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calculadora'
    | '/cronologia'
    | '/efeitos'
    | '/sitemap.xml'
    | '/sobre'
    | '/api/public/payments/webhook'
    | '/api/public/v1/health'
    | '/api/public/v1/montecarlo'
    | '/api/public/v1/recommend-interval'
    | '/api/public/v1/simulate'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calculadora'
    | '/cronologia'
    | '/efeitos'
    | '/sitemap.xml'
    | '/sobre'
    | '/api/public/payments/webhook'
    | '/api/public/v1/health'
    | '/api/public/v1/montecarlo'
    | '/api/public/v1/recommend-interval'
    | '/api/public/v1/simulate'
  id:
    | '__root__'
    | '/'
    | '/calculadora'
    | '/cronologia'
    | '/efeitos'
    | '/sitemap.xml'
    | '/sobre'
    | '/api/public/payments/webhook'
    | '/api/public/v1/health'
    | '/api/public/v1/montecarlo'
    | '/api/public/v1/recommend-interval'
    | '/api/public/v1/simulate'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalculadoraRoute: typeof CalculadoraRoute
  CronologiaRoute: typeof CronologiaRoute
  EfeitosRoute: typeof EfeitosRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SobreRoute: typeof SobreRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
  ApiPublicV1HealthRoute: typeof ApiPublicV1HealthRoute
  ApiPublicV1MontecarloRoute: typeof ApiPublicV1MontecarloRoute
  ApiPublicV1RecommendIntervalRoute: typeof ApiPublicV1RecommendIntervalRoute
  ApiPublicV1SimulateRoute: typeof ApiPublicV1SimulateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/efeitos': {
      id: '/efeitos'
      path: '/efeitos'
      fullPath: '/efeitos'
      preLoaderRoute: typeof EfeitosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cronologia': {
      id: '/cronologia'
      path: '/cronologia'
      fullPath: '/cronologia'
      preLoaderRoute: typeof CronologiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculadora': {
      id: '/calculadora'
      path: '/calculadora'
      fullPath: '/calculadora'
      preLoaderRoute: typeof CalculadoraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/simulate': {
      id: '/api/public/v1/simulate'
      path: '/api/public/v1/simulate'
      fullPath: '/api/public/v1/simulate'
      preLoaderRoute: typeof ApiPublicV1SimulateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/recommend-interval': {
      id: '/api/public/v1/recommend-interval'
      path: '/api/public/v1/recommend-interval'
      fullPath: '/api/public/v1/recommend-interval'
      preLoaderRoute: typeof ApiPublicV1RecommendIntervalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/montecarlo': {
      id: '/api/public/v1/montecarlo'
      path: '/api/public/v1/montecarlo'
      fullPath: '/api/public/v1/montecarlo'
      preLoaderRoute: typeof ApiPublicV1MontecarloRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/health': {
      id: '/api/public/v1/health'
      path: '/api/public/v1/health'
      fullPath: '/api/public/v1/health'
      preLoaderRoute: typeof ApiPublicV1HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalculadoraRoute: CalculadoraRoute,
  CronologiaRoute: CronologiaRoute,
  EfeitosRoute: EfeitosRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SobreRoute: SobreRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
  ApiPublicV1HealthRoute: ApiPublicV1HealthRoute,
  ApiPublicV1MontecarloRoute: ApiPublicV1MontecarloRoute,
  ApiPublicV1RecommendIntervalRoute: ApiPublicV1RecommendIntervalRoute,
  ApiPublicV1SimulateRoute: ApiPublicV1SimulateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
