/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as EfeitosRouteImport } from './routes/efeitos'
import { Route as CronologiaRouteImport } from './routes/cronologia'
import { Route as CalculadoraRouteImport } from './routes/calculadora'
import { Route as IndexRouteImport } from './routes/index'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const EfeitosRoute = EfeitosRouteImport.update({
  id: '/efeitos',
  path: '/efeitos',
  getParentRoute: () => rootRouteImport,
} as any)
const CronologiaRoute = CronologiaRouteImport.update({
  id: '/cronologia',
  path: '/cronologia',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculadoraRoute = CalculadoraRouteImport.update({
  id: '/calculadora',
  path: '/calculadora',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calculadora': typeof CalculadoraRoute
  '/cronologia': typeof CronologiaRoute
  '/efeitos': typeof EfeitosRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calculadora': typeof CalculadoraRoute
  '/cronologia': typeof CronologiaRoute
  '/efeitos': typeof EfeitosRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calculadora': typeof CalculadoraRoute
  '/cronologia': typeof CronologiaRoute
  '/efeitos': typeof EfeitosRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/calculadora' | '/cronologia' | '/efeitos' | '/sitemap.xml'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/calculadora' | '/cronologia' | '/efeitos' | '/sitemap.xml'
  id:
    | '__root__'
    | '/'
    | '/calculadora'
    | '/cronologia'
    | '/efeitos'
    | '/sitemap.xml'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalculadoraRoute: typeof CalculadoraRoute
  CronologiaRoute: typeof CronologiaRoute
  EfeitosRoute: typeof EfeitosRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/efeitos': {
      id: '/efeitos'
      path: '/efeitos'
      fullPath: '/efeitos'
      preLoaderRoute: typeof EfeitosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cronologia': {
      id: '/cronologia'
      path: '/cronologia'
      fullPath: '/cronologia'
      preLoaderRoute: typeof CronologiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculadora': {
      id: '/calculadora'
      path: '/calculadora'
      fullPath: '/calculadora'
      preLoaderRoute: typeof CalculadoraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalculadoraRoute: CalculadoraRoute,
  CronologiaRoute: CronologiaRoute,
  EfeitosRoute: EfeitosRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
